export const ADD_TO_CART = "ADD_TO_CART";
export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";

export const SET_PRODUCTS_VIEW_STYLE_SUCCESS =
  "SET_PRODUCTS_VIEW_STYLE_SUCCESS";

export const LOAD_MORE_PRODUCTS_START = "LOAD_MORE_PRODUCTS_START";
export const LOAD_MORE_PRODUCTS_SUCCESS = "LOAD_MORE_PRODUCTS_SECCESS";
export const LOAD_MORE_PRODUCTS_FAILURE = "LOAD_MORE_PRODUCTS_FAILURE";

export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
