export const ADD_TO_CART = "ADD_TO_CART";
export const CHECKOUT_REQUEST = "CHECKOUT_REQUEST";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_FAILURE = "CHECKOUT_FAILURE";
export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";

export const SET_PRODUCTS_VIEW_STYLE_SUCCESS =
  "SET_PRODUCTS_VIEW_STYLE_SUCCESS";

export const LOAD_MORE_PRODUCTS_START = "LOAD_MORE_PRODUCTS_START";
export const LOAD_MORE_PRODUCTS_SUCCESS = "LOAD_MORE_PRODUCTS_SECCESS";
export const LOAD_MORE_PRODUCTS_FAILURE = "LOAD_MORE_PRODUCTS_FAILURE";

export const SEARCH_PRODUCT = "SEARCH_PRODUCT";

export const FETCH_PRODUCTS_GROUPS_START = "FETCH_PRODUCTS_GROUPS_START";
export const FETCH_PRODUCTS_GROUPS_SUCCESS = "FETCH_PRODUCTS_GROUPS_SUCCESS";
export const FETCH_PRODUCTS_GROUPS_FAILURE = "FETCH_PRODUCTS_GROUPS_FAILURE";

export const GET_ID_PRODUCT_SPECIAL_OFFERS = "GET_ID_PRODUCT_SPECIAL_OFFERS";

// SPECIAL_OFFERS_SETTINGS
export const LOAD_SO_SETTINGS_START = "LOAD_SO_SETTINGS_START";
export const LOAD_SO_SETTINGS_SUCCESS = "LOAD_SO_SETTINGS_SUCCESS";
export const LOAD_SO_SETTINGS_FAILURE = "LOAD_SO_SETTINGS_FAILURE";
